"""
Professional Excel calculation sheet export (Section 26 of the specification).

Builds a multi-sheet, formatted .xlsx workbook using OpenPyXL:
    Sheet 1 - Summary
    Sheet 2 - Initial Inputs
    Sheet 3 - Discharging Calculation
    Sheet 4 - Charging Calculation
    Sheet 5 - RTE

This module has no Streamlit dependency - it operates purely on the calculation
engine's dataclasses, so it can be reused for automated report generation or a
future API.
"""

from __future__ import annotations

from io import BytesIO
from typing import List

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from calculations.models import (
    ProjectInputs, ACEfficiencyChain, DischargeYearInput, ChargeYearInput,
    DischargeSettings, ChargeSettings, DischargeYearResult, ChargeYearResult, RTEYearResult,
)

NAVY = "0B1E3D"
NAVY_LIGHT = "1A3563"
ACCENT = "2F6FED"
LIGHT_GREY = "F4F6FA"
WHITE = "FFFFFF"

HEADER_FONT = Font(name="Calibri", size=11, bold=True, color=WHITE)
HEADER_FILL = PatternFill(start_color=NAVY, end_color=NAVY, fill_type="solid")
SUBHEADER_FONT = Font(name="Calibri", size=10, bold=True, color=WHITE)
SUBHEADER_FILL = PatternFill(start_color=NAVY_LIGHT, end_color=NAVY_LIGHT, fill_type="solid")
TITLE_FONT = Font(name="Calibri", size=16, bold=True, color=NAVY)
LABEL_FONT = Font(name="Calibri", size=10, bold=True, color=NAVY)
VALUE_FONT = Font(name="Calibri", size=10, color="10213E")
THIN_BORDER = Border(
    left=Side(style="thin", color="D5DCE8"), right=Side(style="thin", color="D5DCE8"),
    top=Side(style="thin", color="D5DCE8"), bottom=Side(style="thin", color="D5DCE8"),
)


def _style_header_row(ws, row_idx: int, num_cols: int, sub=False):
    font = SUBHEADER_FONT if sub else HEADER_FONT
    fill = SUBHEADER_FILL if sub else HEADER_FILL
    for c in range(1, num_cols + 1):
        cell = ws.cell(row=row_idx, column=c)
        cell.font = font
        cell.fill = fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = THIN_BORDER


def _autofit_columns(ws, min_width=12, max_width=42):
    widths = {}
    for row in ws.iter_rows():
        for cell in row:
            if cell.value is None:
                continue
            col = cell.column_letter
            length = len(str(cell.value))
            widths[col] = max(widths.get(col, 0), length)
    for col, w in widths.items():
        ws.column_dimensions[col].width = max(min_width, min(max_width, w + 3))


def _title(ws, text, row=1, span=6):
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=span)
    cell = ws.cell(row=row, column=1, value=text)
    cell.font = TITLE_FONT
    cell.alignment = Alignment(horizontal="left", vertical="center")
    ws.row_dimensions[row].height = 28


def _write_table(ws, start_row, headers, rows, sub=False):
    """Write a header row + data rows starting at start_row. Returns the next free row."""
    for c, h in enumerate(headers, start=1):
        ws.cell(row=start_row, column=c, value=h)
    _style_header_row(ws, start_row, len(headers), sub=sub)

    r = start_row + 1
    for row_data in rows:
        for c, val in enumerate(row_data, start=1):
            cell = ws.cell(row=r, column=c, value=val)
            cell.font = VALUE_FONT
            cell.border = THIN_BORDER
            if isinstance(val, float):
                cell.number_format = "#,##0.000"
        r += 1
    ws.freeze_panes = ws.cell(row=start_row + 1, column=1)
    return r + 1


def build_excel_workbook(
    project_name: str,
    proj: ProjectInputs,
    discharge_ac: ACEfficiencyChain,
    charge_ac: ACEfficiencyChain,
    discharge_settings: DischargeSettings,
    charge_settings: ChargeSettings,
    discharge_years: List[DischargeYearInput],
    charge_years: List[ChargeYearInput],
    discharge_results: List[DischargeYearResult],
    charge_results: List[ChargeYearResult],
    rte_results: List[RTEYearResult],
) -> bytes:
    wb = Workbook()

    # ---------------------------------------------------------------
    # Sheet 1: Summary
    # ---------------------------------------------------------------
    ws = wb.active
    ws.title = "Summary"
    _title(ws, f"BESS Sizing Calculation Sheet \u2014 {project_name}")
    ws.cell(row=2, column=1, value="Generated by BESS Sizing Calculation Software").font = Font(italic=True, size=9, color="5C6B85")

    row = 4
    ws.cell(row=row, column=1, value="Key BESS Parameters").font = LABEL_FONT
    _style_header_row(ws, row, 2, sub=True)
    ws.cell(row=row, column=2, value="")
    row += 1
    kv_pairs = [
        ("Container Capacity (MWh)", proj.container_capacity_mwh),
        ("Initial Number of Containers", proj.num_containers_initial),
        ("Initial Installed Capacity (MWh)", proj.initial_installed_capacity_mwh),
        ("Aux Consumption per Container \u2014 Discharge (MW)", proj.aux_consumption_discharge_mw),
        ("Aux Consumption per Container \u2014 Charge (MW)", proj.aux_consumption_charge_mw),
    ]
    for label, val in kv_pairs:
        ws.cell(row=row, column=1, value=label).font = VALUE_FONT
        c = ws.cell(row=row, column=2, value=val)
        c.font = VALUE_FONT
        c.number_format = "#,##0.000"
        row += 1

    row += 1
    if discharge_results:
        d0 = discharge_results[0]
        ws.cell(row=row, column=1, value=f"Final Discharge Results (Year {d0.year})").font = LABEL_FONT
        _style_header_row(ws, row, 2, sub=True)
        row += 1
        for label, val in [
            ("Guaranteed DC Discharge Capacity (MWh)", d0.guarantee_dc_capacity_mwh),
            ("POI Capacity Excl. Aux (MWh)", d0.poi_capacity_excl_aux_mwh),
            ("Aux Energy Discharge (MWh)", d0.aux_energy_discharge_mwh),
            ("POI Capacity Incl. Aux (MWh)", d0.poi_capacity_incl_aux_mwh),
            ("Discharge Time (h)", d0.discharge_time_hours),
        ]:
            ws.cell(row=row, column=1, value=label).font = VALUE_FONT
            c = ws.cell(row=row, column=2, value=val)
            c.font = VALUE_FONT
            c.number_format = "#,##0.000"
            row += 1

    row += 1
    if charge_results:
        c0 = charge_results[0]
        ws.cell(row=row, column=1, value=f"Final Charging Results (Year {c0.year})").font = LABEL_FONT
        _style_header_row(ws, row, 2, sub=True)
        row += 1
        for label, val in [
            ("Charge Guarantee Capacity Excl. Aux (MWh)", c0.charge_guarantee_excl_aux_mwh),
            ("Aux Energy Charge (MWh)", c0.aux_energy_charge_mwh),
            ("Charge Guarantee Capacity Incl. Aux (MWh)", c0.charge_guarantee_incl_aux_mwh),
            ("Charge Time (h)", c0.charge_time_hours),
        ]:
            ws.cell(row=row, column=1, value=label).font = VALUE_FONT
            c = ws.cell(row=row, column=2, value=val)
            c.font = VALUE_FONT
            c.number_format = "#,##0.000"
            row += 1

    row += 1
    if rte_results:
        r0 = rte_results[0]
        ws.cell(row=row, column=1, value=f"RTE Results (Year {r0.year})").font = LABEL_FONT
        _style_header_row(ws, row, 2, sub=True)
        row += 1
        for label, val in [
            ("DC-DC RTE (%)", r0.dc_dc_rte_pct),
            ("AC RTE Excl. Aux (%)", r0.ac_rte_excl_aux_pct),
            ("AC RTE Incl. Aux (%)", r0.ac_rte_incl_aux_pct),
        ]:
            ws.cell(row=row, column=1, value=label).font = VALUE_FONT
            c = ws.cell(row=row, column=2, value=val)
            c.font = VALUE_FONT
            c.number_format = "0.00\"%\""
            row += 1

    _autofit_columns(ws)

    # ---------------------------------------------------------------
    # Sheet 2: Initial Inputs
    # ---------------------------------------------------------------
    ws2 = wb.create_sheet("Initial Inputs")
    _title(ws2, "Initial BESS Inputs", span=3)
    headers = ["Parameter", "Value", "Unit"]
    rows = [
        ("DC Installed Capacity per Container", proj.container_capacity_mwh, "MWh"),
        ("Initial Number of Containers", proj.num_containers_initial, "Nos."),
        ("Initial Installed Capacity (calculated)", proj.initial_installed_capacity_mwh, "MWh"),
        ("Aux Consumption per Container \u2014 Discharge", proj.aux_consumption_discharge_mw, "MW"),
        ("Aux Consumption per Container \u2014 Charge", proj.aux_consumption_charge_mw, "MW"),
    ]
    _write_table(ws2, 3, headers, rows)

    row2 = 3 + len(rows) + 3
    ws2.cell(row=row2, column=1, value="Discharging AC-Side Efficiencies (%)").font = LABEL_FONT
    row2 += 1
    d_ac_rows = [(label, val, "%") for label, val in discharge_ac.as_list()]
    row2 = _write_table(ws2, row2, headers, d_ac_rows, sub=True)

    ws2.cell(row=row2, column=1, value="Charging AC-Side Efficiencies (%)").font = LABEL_FONT
    row2 += 1
    c_ac_rows = [(label, val, "%") for label, val in charge_ac.as_list()]
    row2 = _write_table(ws2, row2, headers, c_ac_rows, sub=True)

    ws2.cell(row=row2, column=1, value="Discharge / Charge Duration & RTE Settings").font = LABEL_FONT
    row2 += 1
    duration_rows = [
        ("Discharge Time Mode", discharge_settings.time_mode.value, ""),
        ("Discharge Time (resolved)", None, "h"),
        ("Discharge C-rate (resolved)", None, "C"),
        ("Charge Time Mode", charge_settings.time_mode.value, ""),
        ("DC-DC RTE", charge_settings.dc_dc_rte_pct, "%"),
    ]
    _write_table(ws2, row2, headers, duration_rows, sub=True)
    _autofit_columns(ws2)

    # ---------------------------------------------------------------
    # Sheet 3: Discharging Calculation
    # ---------------------------------------------------------------
    ws3 = wb.create_sheet("Discharging Calculation")
    _title(ws3, "Discharging Calculation \u2014 Year-wise Detail", span=10)
    headers3 = [
        "Year", "Enclosures", "Container Cap. (MWh)", "Installed DC (MWh)",
        "Availability (%)", "DC Discharge Eff. (%)", "SOH (%)", "Cal. Degradation (%)",
        "DOD (%)", "Guaranteed DC Discharge (MWh)", "DC Usable Energy (MWh)",
        "AC Eff. Product", "Aux Load (MW)", "Discharge Time (h)", "Aux Energy (MWh)",
        "POI Excl. Aux (MWh)", "POI Incl. Aux (MWh)",
    ]
    year_map = {yi.year: yi for yi in discharge_years}
    rows3 = []
    for r in discharge_results:
        yi = year_map.get(r.year)
        rows3.append((
            r.year, yi.enclosures if yi else None, proj.container_capacity_mwh, r.installed_dc_capacity_mwh,
            yi.availability_pct if yi else None, yi.dc_discharge_efficiency_pct if yi else None,
            yi.soh_pct if yi else None, yi.calendar_degradation_pct if yi else None,
            yi.dod_pct if yi else None, r.guarantee_dc_capacity_mwh, r.dc_usable_energy_mwh,
            r.ac_efficiency_product, r.aux_load_discharge_mw, r.discharge_time_hours,
            r.aux_energy_discharge_mwh, r.poi_capacity_excl_aux_mwh, r.poi_capacity_incl_aux_mwh,
        ))
    _write_table(ws3, 3, headers3, rows3)

    row3 = 3 + len(rows3) + 3
    ws3.cell(row=row3, column=1, value="Discharging AC-Side Efficiency Chain (%)").font = LABEL_FONT
    row3 += 1
    _write_table(ws3, row3, ["Stage", "Efficiency (%)"], [(l, v) for l, v in discharge_ac.as_list()], sub=True)
    _autofit_columns(ws3)

    # ---------------------------------------------------------------
    # Sheet 4: Charging Calculation
    # ---------------------------------------------------------------
    ws4 = wb.create_sheet("Charging Calculation")
    _title(ws4, "Charging Calculation \u2014 Year-wise Detail", span=10)
    headers4 = [
        "Year", "Enclosures", "Container Cap. (MWh)", "Installed DC (MWh)",
        "Availability (%)", "DC Charge Eff. (%)", "SOH (%)", "Cal. Degradation (%)",
        "DOD (%)", "DC Usable Energy (MWh)", "AC Eff. Product", "DC-DC RTE (%)",
        "Charge Guarantee Excl. Aux (MWh)", "Aux Load (MW)", "Charge Time (h)",
        "Aux Energy (MWh)", "Charge Guarantee Incl. Aux (MWh)",
    ]
    c_year_map = {yi.year: yi for yi in charge_years}
    rows4 = []
    for r in charge_results:
        yi = c_year_map.get(r.year)
        rows4.append((
            r.year, yi.enclosures if yi else None, proj.container_capacity_mwh, r.installed_dc_capacity_mwh,
            yi.availability_pct if yi else None, yi.dc_charge_efficiency_pct if yi else None,
            yi.soh_pct if yi else None, yi.calendar_degradation_pct if yi else None,
            yi.dod_pct if yi else None, r.dc_usable_energy_mwh, r.ac_efficiency_product,
            charge_settings.dc_dc_rte_pct, r.charge_guarantee_excl_aux_mwh, r.aux_load_charge_mw,
            r.charge_time_hours, r.aux_energy_charge_mwh, r.charge_guarantee_incl_aux_mwh,
        ))
    _write_table(ws4, 3, headers4, rows4)

    row4 = 3 + len(rows4) + 3
    ws4.cell(row=row4, column=1, value="Charging AC-Side Efficiency Chain (%)").font = LABEL_FONT
    row4 += 1
    _write_table(ws4, row4, ["Stage", "Efficiency (%)"], [(l, v) for l, v in charge_ac.as_list()], sub=True)
    _autofit_columns(ws4)

    # ---------------------------------------------------------------
    # Sheet 5: RTE
    # ---------------------------------------------------------------
    ws5 = wb.create_sheet("RTE")
    _title(ws5, "Round-Trip Efficiency (RTE) \u2014 Year-wise", span=4)
    headers5 = ["Year", "DC-DC RTE (%)", "AC RTE Excl. Aux (%)", "AC RTE Incl. Aux (%)"]
    rows5 = [(r.year, r.dc_dc_rte_pct, r.ac_rte_excl_aux_pct, r.ac_rte_incl_aux_pct) for r in rte_results]
    _write_table(ws5, 3, headers5, rows5)
    _autofit_columns(ws5)

    # Output to bytes
    buffer = BytesIO()
    wb.save(buffer)
    return buffer.getvalue()
